# Generated by Django 5.0.2 on 2024-02-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='category',
            field=models.CharField(blank=True, choices=[('msc', 'Music Art'), ('dig', 'Digital Art'), ('blc', 'Blockchain'), ('vtr', 'Virtual')], max_length=600, null=True),
        ),
    ]
