# Generated by Django 5.0.2 on 2024-02-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nft_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='category',
            field=models.CharField(choices=[('msc', 'Music Art'), ('dig', 'Digital Art'), ('blc', 'Blockchain'), ('vtr', 'Virtual')], default='timezone.now', max_length=600),
            preserve_default=False,
        ),
    ]
